before_install:
    - gem update --system
    - gem install bundler
    - bundle install
    - bundle exec pod install --repo-update
    - gem install linterbot
    - brew install swiftlint
cache:
  - bundler
  - cocoapods
language: objective-c
osx_image: xcode10
xcode_project: DemoConfigiOSProject.xcworkspace
xcode_scheme: [DEV]-DemoConfigiOSProject
xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone X
script:
    - ./scripts/lint
    - xcodebuild clean build -sdk iphonesimulator -workspace DemoConfigiOSProject.xcworkspace -scheme [DEV]-DemoConfigiOSProject CODE_SIGNING_REQUIRED=NO
install:
    - sudo systemsetup -settimezone Asia/Ho_Chi_Minh