before_install:
    - gem update --system
    - gem install bundler
    - bundle install
    - bundle exec pod install --repo-update
cache:
  - bundler
  - cocoapods
language: objective-c
osx_image: xcode10
xcode_project: ConfigProject.xcworkspace
xcode_scheme: Dev
xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone X
script:
    - xcodebuild clean build -sdk iphonesimulator -workspace ConfigProject.xcworkspace -scheme Dev CODE_SIGNING_REQUIRED=NO
install:
    - sudo systemsetup -settimezone Asia/Ho_Chi_Minh